# Generated by Django 3.1.3 on 2022-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson',
            new_name='lesson_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
